#!/usr/bin/env ruby

path    = File.dirname(__FILE__)

$pids   = []
scripts = %w(redis-server private_pub resque scheduler).map{|s| "#{path}/#{s}"}


def run script
  print "starting #{script} pid:"
  $pids << fork { system script }
  puts $pids.last
end

def kill pid
  Process.kill 'HUP', pid
end

def kill_all
  $pids.each {|pid| kill pid}
end


begin
  scripts.each {|script| run script}

  print '^C to shut down'
  loop {}
rescue SystemExit, Interrupt
  kill_all
rescue Exception => e
  puts 'error', e.inspect
end
